services:
  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      etcd:
        condition: service_healthy

    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.0-alpine
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      apisix:
    depends_on:
      etcd:
        condition: service_healthy
  tag-microservice:
    build: .
    container_name: tag-microservice
    depends_on:
      mysql-db:
        condition: service_healthy
      apisix:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=tag-microservice
      - MYSQL_USER=ryan
      - MYSQL_PASSWORD=831374
      - MYSQL_ROOT_PASSWORD=831374
    networks:
      apisix:

  mysql-db:
    image: mysql:8.0.36
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=tag-microservice
      - MYSQL_USER=ryan
      - MYSQL_PASSWORD=831374
      - MYSQL_ROOT_PASSWORD=831374
    volumes:
      - mysql-tag-microservice:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      apisix:

volumes:
  mysql-tag-microservice:
  etcd_data:
    driver: local
networks:
  apisix:
    driver: bridge
