version: "3.8"

services:
  tag-microservice:
    build: .
    container_name: tag-microservice
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=tag-microservice
      - MYSQL_USER=ryan
      - MYSQL_PASSWORD=831374
      - MYSQL_ROOT_PASSWORD=831374

  mysql-db:
    image: mysql:8.0.36
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=tag-microservice
      - MYSQL_USER=ryan
      - MYSQL_PASSWORD=831374
      - MYSQL_ROOT_PASSWORD=831374
    volumes:
      - mysql-tag-microservice:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-tag-microservice:
