apisix:
  node_listen: 9080
  enable_ipv6: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092
  allow_admin:
    - 0.0.0.0/0
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

routes:
  - id: 1
    uri: /api/tags
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 2
    uri: /api/tags
    methods: ["PUT"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 3
    uri: /api/tags
    methods: ["DELETE"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 4
    uri: /api/tags/id
    methods: ["GET"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 5
    uri: /api/tags/approve
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 6
    uri: /api/tags/reject
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 7
    uri: /api/tags/merge
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 8
    uri: /api/taxonomies
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 9
    uri: /api/taxonomies
    methods: ["PUT"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 10
    uri: /api/related-tags/key
    methods: ["GET"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 11
    uri: /api/related-tags/id
    methods: ["GET"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 12
    uri: /api/related-tags/search
    methods: ["GET"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1

  - id: 13
    uri: /api/tags
    methods: ["GET"]
    upstream:
      type: roundrobin
      nodes:
        "app:8080": 1
